
const checkedInUser = async(req,res)=>{
    try{

    }catch(e){
        console.log('error in the checkedInUser',e)
    }
}

const checkUserStatus = async(req,res)=>{
    try{

    }catch(e){
        console.log('error in the checkUserStatus',e);
    }
}